#!/usr/bin/env bash

headset=$(upower -i /org/freedesktop/UPower/devices/headset_dev_14_3F_A6_47_83_F3 | grep % | sed 's/[^0-9]//g')
mouse=$(upower -i /org/freedesktop/UPower/devices/battery_hidpp_battery_0 | grep % | sed 's/[^0-9]//g')

echo " ${headset} ${mouse}"
