#!/usr/bin/perl
use strict;
use warnings;
use utf8;
use Getopt::Long;

# default values
my $cpu_usage = -1;
my $decimals = $ENV{DECIMALS} // 0;
my $chip = $ENV{SENSOR_CHIP} || "coretemp-isa-0000";
my $temperature = -9999;

# Get CPU usage
$ENV{LC_ALL}="en_US"; # if mpstat is not run under en_US locale, things may break, so make sure it is
open (MPSTAT, 'mpstat 1 1 |') or die;
while (<MPSTAT>) {
    if (/^.*\s+(\d+\.\d+)[\s\x00]?$/) {
        $cpu_usage = 100 - $1; # 100% - %idle
        last;
    }
}
close(MPSTAT);

$cpu_usage eq -1 and die 'Can\'t find CPU information';

# Get chip temperature
open (SENSORS, "sensors -u $chip |") or die;
while (<SENSORS>) {
    if (/^\s+temp1_input:\s+[\+]*([\-]*\d+\.\d)/) {
        $temperature = $1;
        last;
    }
}
close(SENSORS);

$temperature eq -9999 and die 'Cannot find temperature';

printf "%02.${decimals}f $temperature\n", $cpu_usage;

exit 0;

